apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-loki-0-pv
  namespace: dhi-13958-loki
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/loki